<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250108002532 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(90) NOT NULL, contato VARCHAR(80) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE orcamento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qtd NUMERIC(5, 2) NOT NULL, valor_total NUMERIC(10, 2) DEFAULT NULL, data TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id_cliente_id INT DEFAULT NULL, id_servico_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4B1DD46D7BF9CE86 ON orcamento (id_cliente_id)');
        $this->addSql('CREATE INDEX IDX_4B1DD46D276BC955 ON orcamento (id_servico_id)');
        $this->addSql('CREATE TABLE servico (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(40) NOT NULL, valor_unid NUMERIC(10, 2) NOT NULL, unid_medida VARCHAR(30) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46D7BF9CE86 FOREIGN KEY (id_cliente_id) REFERENCES cliente (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orcamento ADD CONSTRAINT FK_4B1DD46D276BC955 FOREIGN KEY (id_servico_id) REFERENCES servico (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE orcamento DROP CONSTRAINT FK_4B1DD46D7BF9CE86');
        $this->addSql('ALTER TABLE orcamento DROP CONSTRAINT FK_4B1DD46D276BC955');
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE orcamento');
        $this->addSql('DROP TABLE servico');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
